repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: check-symlinks
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.2"]
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--atomic", "--profile", "black"]
        language_version: python3.11
