# Generated by Django 5.1.2 on 2025-01-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_map_owner_alter_map_last_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='position_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tile',
            name='position_y',
            field=models.IntegerField(default=0),
        ),
    ]
